# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Security updates for production dependencies in the develop branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "gerrymiller"
    labels:
      - "dependencies"
    target-branch: "develop"
    open-pull-requests-limit: 10
    security-updates: true

  # Regular updates for production dependencies in the develop branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "gerrymiller"
    labels:
      - "dependencies"
    target-branch: "develop"
    open-pull-requests-limit: 10

      # Security updates for production dependencies in the main branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "gerrymiller"
    labels:
      - "dependencies"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
    open-pull-requests-limit: 0
    security-updates: true

  # Regular updates for production dependencies in the main branch
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "gerrymiller"
    labels:
      - "dependencies"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
    open-pull-requests-limit: 0
